#!/bin/bash
# Monitor current download progress and show recent activity

echo "=== Current Download Status ==="
echo ""
echo "Process: RUNNING (PID: $(pgrep -f download_football_logos.py))"
echo "Downloaded so far: $(find football_logos -name "*.svg" -path "*/svg/*" | wc -l | tr -d ' ') SVGs"
echo ""
echo "To see live output, the download is running in your terminal."
echo "Failures are printed as they happen with '✗' markers."
echo ""
echo "=== For Better Logging Next Time ==="
echo ""
echo "1. Stop current download: kill $(pgrep -f download_football_logos.py)"
echo ""
echo "2. Restart with logging:"
echo "   source venv/bin/activate"
echo "   python download_football_logos.py --format svg --delay 1.0 2>&1 | tee download.log"
echo ""
echo "3. Then you can:"
echo "   - View all output: cat download.log"
echo "   - View only failures: grep '✗' download.log"
echo "   - Count failures: grep -c '✗' download.log"
echo "   - See 404 errors: grep '404' download.log"
echo "   - See rate limit errors: grep '429' download.log"
